version: "2"

services:

  graphsense-rest:
    image: graphsense-rest
    container_name: graphsense-rest
    hostname: graphsense-rest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NUM_WORKERS: "${NUM_WORKERS}"
    volumes:
     - "$PWD/rest_data:/usr/var/data/"
    ports:
      - "$REST_PORT:9000"
    restart: always
    networks:
     - graphsense-global-net
networks:
  graphsense-global-net:
    external: true
